### ISSUE TITLE
unicode char in README.rst breaks installation with Python 3 and C locale

### ISSUE THREAD

**Issue by tetron** [closeio/ciso8601#32]
When installing ciso8601 as a package dependency, using Python 3 and C locale:

```
Searching for ciso8601
Reading https://pypi.python.org/simple/ciso8601/
Downloading https://pypi.python.org/packages/06/2e/2d7b09bb667bd7d862838c1ab7d0dd06be1de27ff60a7c1b0fb0db53fc93/ciso8601-1.0.5.tar.gz#md5=831bbf799722d34a5e60d91e1fd63cd6
Best match: ciso8601 1.0.5
Processing ciso8601-1.0.5.tar.gz
Writing /tmp/easy_install-b_gqrezf/ciso8601-1.0.5/setup.cfg
Running ciso8601-1.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-b_gqrezf/ciso8601-1.0.5/egg-dist-tmp-e66bnce5
Traceback (most recent call last):
  File "/var/lib/arvados/test/VENV3DIR/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/var/lib/arvados/test/VENV3DIR/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/var/lib/arvados/test/VENV3DIR/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/var/lib/arvados/test/VENV3DIR/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-b_gqrezf/ciso8601-1.0.5/setup.py", line 4, in <module>
    # SPDX-License-Identifier: Apache-2.0
  File "/var/lib/arvados/test/VENV3DIR/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1561: ordinal not in range(128)
```

This is caused by non-ASCII character "µs" in `README.rst`

With some googling I found a discussion about this same problem relating to a different package:

https://github.com/crsmithdev/arrow/issues/208

**Comment by anemitz** [comment]
@tetron how would you propose solving this in the project? PR welcome:)

**Comment by annp89** [comment]
@anemitz I ran into this same issue. Could you please review PR #33 and provide feedback? It would be great to resolve this issue. Thanks!!

**Comment by norpol** [comment]
Thanks for bumping @annp89, in addition, I've just sent @anemitz an mail to the address mentioned in their profile page.

**Comment by annp89** [comment]
Oh yay!! this is great news. thanks for responding so quickly. Appreciate your time.

**Comment by annp89** [comment]
Will this be added to a minor version release?

**Comment by movermeyer** [comment]
Until this is released, you can work around the issue by [manually setting your locale to UTF-8](https://webkul.com/blog/setup-locale-python3/) in your Dockerfile.

```dockerfile
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
```
